name: Build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Installation
        run: npm ci

      - name: Create config
        run: | 
          echo $CONFIG_JSON > ./src/config.json
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_FILE }}
  
      - name: Check
        run: npm run check

      - name: Build
        run: npm run build:tsc

      - name: Lint
        run: npm run lint